### PR TITLE
bug(#307): check for `LtUnlint` in `PkMono`

### LINKED ISSUE #307: `LtAsciiOnly` and `LtTestNotVerb` not wrapper in any Unlint Wrapper
In [PkMono](https://github.com/objectionary/lints/blob/5f5cd402bdb82627d39c4a2212bf97baa59d4858/src/main/java/org/eolang/lints/PkMono.java) creates `LtAsciiOnly` and `LtTestNotVerb`, but they are not wrapped by any Unlint

So if I understand correctly, ignoring these warnings will not work

### PR DESCRIPTION
**Pull request by h1alexbel**
In this PR I've wrapped lints in `PkMono` with `LtUnlint`. Besides that, I added tests that check that each lint can be unlinted.

closes #307
History:
- **bug(#307): +LtUnlint**
- **bug(#307): can be unlinted**
- **bug(#307): filter LtIncorrectUnlint**
- **bug(#307): clean for qulice**

### CODE REVIEW

**Comment by h1alexbel** [comment]
@yegor256 take a look, please

File: src/main/java/org/eolang/lints/PkMono.java [hunk 1]
```diff
@@ -54,7 +54,7 @@ final class PkMono extends IterableEnvelope<Lint<XML>> {
         new Joined<Lint<XML>>(
             new PkByXsl(),
             List.of(
-                new LtAsciiOnly()
+                new LtUnlint(new LtAsciiOnly())
```
Comment (yegor256) [inline src/main/java/org/eolang/lints/PkMono.java:57]: @h1alexbel maybe it's better to do the mapping, with the help of `Mapped`, as it's done in `PkByXsl`?

**Review by yegor256 — CHANGES_REQUESTED** [review]
@h1alexbel I think we should remove it from `PkByXsl` too

**Comment by h1alexbel** [comment]
@yegor256 updated. Take a look, please

**Comment by yegor256** [comment]
@h1alexbel thanks!
