### PR TITLE
bug(#143): Measure lint time for S/M/L/XL/XXL-sized programs in `ProgramTest`

### LINKED ISSUE #143: ProgramTest.java:54-58: Measure lint time for...
The puzzle `134-6f7709d5` from #134 has to be resolved: 

https://github.com/objectionary/lints/blob/ec352ec8a9402693173483008c87a0dbf2dd6028/src/test/java/org/eolang/lints/ProgramTest.java#L54-L58

The puzzle was created by @yegor256 on 13-Dec-24. 

Estimate: 45 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by h1alexbel**
In this PR I've introduced lint time measurements for `S`, `M`, `L`, `XL`, `XXL`-sized program, based on executable lines in Java `.class` file, from which we prepare XMIR.

closes #143
History:
- **feat(#143): java to XMIR**
- **feat(#143): ProgramSize**
- **feat(#143): check lines with asm**
- **feat(#143): simplified**
- **feat(#143): clean up**
- **feat(#143): clean for qulice**
- **feat(#134): hadoop**
- **feat(#134): clean for qulice**

### CODE REVIEW

**Comment by h1alexbel** [comment]
@volodya-lombrozo could you take a look, please

File: src/test/java/fixtures/ProgramBenches.java [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+    /**
+     * Program size.
+     * @since 0.0.45
+     */
+    public enum ProgramSize {
+
+        /**
+         * Standard program.
+         */
+        S("S", 5, 50),
```
Comment (volodya-lombrozo) [inline src/test/java/fixtures/ProgramBenches.java:40]: @h1alexbel Can we add one more parameter `bytecode` to the `ProgramSize`?

What I mean to say, instead of:

```java
S("S", 5, 50)
```

We might  define it as follows: 

```java
S("S", 5, 50, "com/sun/jna/PointerType.class")
```

Then you will be able to rename `ProgramSize` -> `ProgramBenches` and toss out the `Map<ProgramBenches.ProgramSize, String> value()` method.

What do you think?

File: src/test/java/org/eolang/lints/ProgramTest.java [hunk 2]
```diff
@@ -287,28 +290,79 @@ void returnsOnlyOneDefect() throws IOException {
...
     @Timeout(600L)
-    void lintsLargeJnaClass() throws Exception {
-        final String path = "com/sun/jna/Pointer.class";
-        final XML xmir = new Unchecked<>(new LargeXmir()).value();
-        final long start = System.currentTimeMillis();
-        final Collection<Defect> defects = new ProgramTest.BcProgram(xmir).defects();
-        final long msec = System.currentTimeMillis() - start;
-        final Path target = Paths.get("target");
+    void lintsBenchmarkProgramsFromJava() throws Exception {
+        final StringBuilder sum = new StringBuilder(256);
```
Comment (volodya-lombrozo) [inline src/test/java/org/eolang/lints/ProgramTest.java:294]: @h1alexbel Why `256`?  [Magic number](https://en.wikipedia.org/wiki/Magic_number_(programming))?

File: src/test/java/org/eolang/lints/ProgramTest.java [hunk 3]
```diff
@@ -388,4 +455,47 @@ public Collection<Defect> defects() {
             }
         }
     }
+
+    /**
+     * Line number visitor.
+     * @since 0.0.45
+     */
+    private static final class LineCountVisitor extends ClassVisitor {
```
Comment (volodya-lombrozo) [inline src/test/java/org/eolang/lints/ProgramTest.java:463]: @h1alexbel Line numbers are optional in bytecode. If compiler decides to skip them, you will get `0` here. However, as I understand, all of the classes, you are using, are compiled with lines. So, it's not an issue for now. Thus, I suggest just mentioning this somewhere in javadocs.

File: src/test/java/org/eolang/lints/ProgramTest.java [hunk 4]
```diff
@@ -333,19 +387,26 @@ private static final class BcProgram {
          */
         private final Tojos timings;
 
+        /**
+         * Size marker of the program.
+         */
+        private final String marker;
```
Comment (volodya-lombrozo) [inline src/test/java/org/eolang/lints/ProgramTest.java:393]: @h1alexbel [opinionated] `marker` is a bit misleading, as for me. Maybe we can rename it to `length`? What do you think?

File: src/test/java/org/eolang/lints/ProgramTest.java [hunk 5]
```diff
@@ -287,28 +290,79 @@ void returnsOnlyOneDefect() throws IOException {
...
-            "Defects are empty, but they should not be",
-            defects,
-            Matchers.hasSize(Matchers.greaterThan(0))
+    }
+
+    @Test
+    void checksJavaProgramsForBenchmarking() {
+        new ProgramBenches().value().forEach(
+            (size, program) -> {
+                final ProgramTest.LineCountVisitor visitor = new ProgramTest.LineCountVisitor();
```
Comment (volodya-lombrozo) [inline src/test/java/org/eolang/lints/ProgramTest.java:330]: @h1alexbel Do you need this variable somewhere else?
https://www.yegor256.com/2015/09/01/redundant-variables-are-evil.html

**Review by volodya-lombrozo — CHANGES_REQUESTED** [review]

File: pom.xml [hunk 6]
```diff
@@ -209,6 +209,12 @@
       <version>5.17.0</version>
       <scope>test</scope>
     </dependency>
+    <dependency>
+      <groupId>org.apache.hadoop</groupId>
```
[the remark this answers is not in the document]
Comment (h1alexbel) [reply pom.xml:213]: @volodya-lombrozo we use need it in tests in order to access `org/apache/hadoop/hdfs/server/namenode/FSNamesystem.class`:

```java
programs.put(
    ProgramBenches.ProgramSize.XXL,
    "org/apache/hadoop/hdfs/server/namenode/FSNamesystem.class"
);
```

File: .github/workflows/jmh-benchmark-action.yml [hunk 7]
```diff
@@ -0,0 +1,21 @@
+# SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
+# SPDX-License-Identifier: MIT
+---
+name: Performance Regression Check
```
[the remark this answers is not in the document]
Comment (h1alexbel) [reply .github/workflows/jmh-benchmark-action.yml:4]: @volodya-lombrozo agree, I will add puzzle

File: src/test/java/benchmarks/ProgramBench.java [hunk 8]
```diff
@@ -35,23 +35,63 @@
...
+    /**
+     * XXL XMIR document.
      */
-    private static final XML SMALL = new XMLDocument("<program name='foo'/>");
+    private static final XML XXL = new Unchecked<>(
+        new JavaToXmir(new ProgramBenches().value().get(ProgramBenches.ProgramSize.XXL))
+    ).value();
+
+    @Benchmark
+    public final void scansSmallXmir() {
```
[the remark this answers is not in the document]
Comment (h1alexbel) [reply src/test/java/benchmarks/ProgramBench.java:74]: @volodya-lombrozo got it, but we are not using `@Param` in benchmark tests, since we need to pre-load XMIRs statically:

```java
private static final XML SMALL = new Unchecked<>(
    new JavaToXmir(new ProgramBenches().value().get(ProgramBenches.ProgramSize.S))
).value();
```

WDYT?

File: src/test/java/fixtures/JavaToXmir.java [hunk 9]
```diff
@@ -18,47 +18,54 @@
 import org.xembly.Xembler;
 
 /**
- * Large XMIR document.
+ * Java `.class` to XMIR document.
  *
  * @since 0.0.31
  */
-public final class LargeXmir implements Scalar<XML> {
+public final class JavaToXmir implements Scalar<XML> {
```
[the remark this answers is not in the document]
Comment (h1alexbel) [reply src/test/java/fixtures/JavaToXmir.java:25]: @volodya-lombrozo yes, makes sense. I will rename it to `BytecodeClass`

File: pom.xml (hunk 6 above)
[the remark this answers is not in the document]
Comment (volodya-lombrozo) [reply pom.xml:213]: @h1alexbel Can we get some other class from already added dependencies? Otherwise, it's hard to justify the presence of this dependency. And it's too misleading. 
Another option would be adding this class directly to test resources.

File: src/test/java/org/eolang/lints/ProgramTest.java (hunk 4 above)
Comment (h1alexbel) [reply src/test/java/org/eolang/lints/ProgramTest.java:393]: @volodya-lombrozo how about `type`?

File: src/test/java/benchmarks/ProgramBench.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (volodya-lombrozo) [reply src/test/java/benchmarks/ProgramBench.java:74]: @h1alexbel I see your point here. To "pre-load" something for benchmarks, you need to use [State](https://github.com/melix/jmh-gradle-example/blob/master/src/jmh/java/org/openjdk/jmh/samples/JMHSample_03_States.java) together with `@Setup` annotation (`org.openjdk.jmh.annotations.Setup`). By doing this you can init benchmarks with params. 
 
[Here](https://github.com/volodya-lombrozo/xnav/blob/734d63d274cd3f1624e9340a53cd1a509de456e6/src/test/java/com/github/lombrozo/xnav/XmlBenchmark.java#L286) is how you can do it.

File: src/test/java/org/eolang/lints/ProgramTest.java (hunk 2 above)
Comment (volodya-lombrozo) [reply src/test/java/org/eolang/lints/ProgramTest.java]: @h1alexbel Why `64`?

File: src/test/java/org/eolang/lints/ProgramTest.java (hunk 4 above)
Comment (volodya-lombrozo) [reply src/test/java/org/eolang/lints/ProgramTest.java:394]: @h1alexbel  From dictionary:

```
Synonyms: dimensions, measurements, proportions, magnitude, largeness, bigness, bulk, area, expanse, square footage, footage, acreage, breadth, width, length, height, depth, extent, scope, range, scale, volume, capacity, mass, weight, avoirdupois, immensity, amplitude, hugeness, vastness
```
If non of them are suitable, let's leave `type` then. I'm not against it.

File: src/test/java/org/eolang/lints/ProgramTest.java (hunk 2 above)
Comment (h1alexbel) [reply src/test/java/org/eolang/lints/ProgramTest.java]: @volodya-lombrozo this capacity is used to construct the summary of benchmark execution:

```text
Input: com/sun/jna/PointerType.class (S program)
Lint time: 4979[ms]s (4979 ms)

Input: com/sun/jna/Memory.class (M program)
Lint time: 3935[ms]s (3935 ms)

Input: com/sun/jna/Pointer.class (L program)
Lint time: 4772[ms]s (4772 ms)

Input: com/sun/jna/Structure.class (XL program)
Lint time: 6785[ms]s (6785 ms)

Input: org/apache/hadoop/hdfs/server/namenode/FSNamesystem.class (XXL program)
Lint time: 83086[ms]s (83086 ms)
```

To be honest, I'm not sure which size we should specify there. WDYT?

Comment (volodya-lombrozo) [reply src/test/java/org/eolang/lints/ProgramTest.java]: @h1alexbel I would leave it empty `new StringBuilder()`, or if linters complain about it, then `new StringBuilder(0)`

**Comment by h1alexbel** [comment]
@volodya-lombrozo updated. Take a look, please

**Review by volodya-lombrozo — APPROVED** [review]
@h1alexbel Looks good to me! Thank you.

File: pom.xml [hunk 10]
```diff
@@ -505,5 +511,21 @@
         </executions>
       </plugin>
     </plugins>
+    <testResources>
+      <testResource>
+        <directory>src/test/resources</directory>
+        <excludes>
+          <exclude>org/apache/hadoop/hdfs/server/namenode/FSNamesystem.class</exclude>
```
Comment (yegor256) [inline pom.xml:518]: @h1alexbel this definitely is a bad idea -- keeping large binary fixture in the repository. Instead, just use `dependency:unpack` plugin, which you can configure to take only a single `.class` file from the JAR and place it into the `target/` directory.

**Review by yegor256 — CHANGES_REQUESTED** [review]

**Comment by h1alexbel** [comment]
@yegor256 updated. Take a look, please

**Review by yegor256 — APPROVED** [review]

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@volodya-lombrozo Hey there, awesome job on the review! 🎉 You've racked up 11 points for this one: 4 base points, plus a sweet 6 points for those 26 insightful comments you made. That's some quality feedback! Your [running balance](https://www.eolang.org/zerocracy/objectionary-vitals.html) is now at +94. Keep up the great work – your thorough reviews are really helping the team level up our code quality!

**Comment by 0crat** [comment]
@yegor256 Hey there, coding champ! 🎉 Awesome job on that review - you've snagged +11 points! That's +4 for showing up and a sweet +6 for those 26 insightful comments you dropped. Nice work on hitting that 16+ [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html) mark too. Your current balance is sitting at [-887](https://www.eolang.org/zerocracy/objectionary-vitals.html), but keep this up and you'll be climbing that leaderboard in no time. Remember, more comments mean more points, so keep that feedback flowing!

**Comment by 0crat** [comment]
@h1alexbel Hey there, awesome contribution! 🚀 You've earned +4 points for this one. Here's the breakdown: +4 base points, -8 for the 430 hits-of-code (a bit over the 200 limit), -6 for the 32 review comments (we cap that at -16), and +14 to keep you motivated. Remember, [smaller contributions](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) can sometimes earn more points! Your balance is now [+124](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep those contributions coming, and don't hesitate to ask for reviews – they're crucial for earning points!
