### PR TITLE
bug(#396): clear message in incorrect-unlint

### LINKED ISSUE #396: `incorrect-unlint` message is unclear
Getting this:

```text
Uselessly "unlint", because a lint with that name does not exist
```

From this message its not clear what exact `+unlint` meta is broken (unless I have the line numbers in defect). Let's fix it

### PR DESCRIPTION
**Pull request by h1alexbel**
In this PR I've improved defect message in `incorrect-unlint`.

closes #396

### CODE REVIEW

**Comment by h1alexbel** [comment]
@maxonfjvipon please check

File: src/main/java/org/eolang/lints/LtIncorrectUnlint.java [hunk 1]
```diff
@@ -41,22 +40,29 @@ public String name() {
...
+                    final String name = u.element("tail").text().orElse("unknown");
+                    defects.add(
+                        new Defect.Default(
+                            this.name(),
+                            Severity.ERROR,
+                            xml.element("program").attribute("name").text().orElse("unknown"),
+                            Integer.parseInt(u.attribute("line").text().orElse("0")),
+                            String.format(
+                                "Unlinting \"%s\" does not make sense, because there is no lint with that name",
+                                name
```
Comment (maxonfjvipon) [inline src/main/java/org/eolang/lints/LtIncorrectUnlint.java:59]: @h1alexbel it seems we can inline this variable

**Review by maxonfjvipon — CHANGES_REQUESTED** [review]

**Review by maxonfjvipon — APPROVED** [review]

**Comment by h1alexbel** [comment]
@yegor256 take a look, please

File: src/main/java/org/eolang/lints/LtIncorrectUnlint.java [hunk 2]
```diff
@@ -41,22 +40,26 @@ public String name() {
...
+            .filter(u -> !this.names.contains(u.element("tail").text().orElse("unknown")))
+            .forEach(
+                u -> defects.add(
+                    new Defect.Default(
+                        this.name(),
+                        Severity.ERROR,
+                        xml.element("program").attribute("name").text().orElse("unknown"),
+                        Integer.parseInt(u.attribute("line").text().orElse("0")),
+                        String.format(
+                            "Unlinting \"%s\" does not make sense, because there is no lint with that name",
```
Comment (yegor256) [inline src/main/java/org/eolang/lints/LtIncorrectUnlint.java:56]: @h1alexbel maybe just "Suppressing" is a better word?

**Comment by h1alexbel** [comment]
@yegor256 updated. Take a look, please

**Comment by yegor256** [comment]
@h1alexbel thanks!
