### PR TITLE
bug(#478): L sized program in ProgramsBench

### LINKED ISSUE #478: `ProgramsBench.scansLargeProgram()` fails
I run this:

```bash
mvn jmh:benchmark
```

And getting this:

```text
java.lang.IllegalStateException: java.io.IOException: The resource "program-0.xmir" was not found in jdk.internal.loader.ClassLoaders$AppClassLoader@2c854dc5 (jdk.internal.loader.ClassLoaders.AppClassLoader)
	at org.cactoos.Fallback$None.apply(Fallback.java:103)
	at org.cactoos.Fallback$None.apply(Fallback.java:95)
	at org.cactoos.scalar.ScalarWithFallback.fallback(ScalarWithFallback.java:108)
	at org.cactoos.scalar.ScalarWithFallback.value(ScalarWithFallback.java:74)
	at org.cactoos.scalar.Checked.value(Checked.java:56)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:44)
	at org.cactoos.scalar.Unchecked.value(Unchecked.java:37)
	at org.cactoos.bytes.UncheckedBytes.asBytes(UncheckedBytes.java:53)
	at fixtures.BytecodeClass.lambda$value$0(BytecodeClass.java:79)
	at com.yegor256.farea.Farea.together(Farea.java:179)
	at fixtures.BytecodeClass.value(BytecodeClass.java:67)
	at fixtures.BytecodeClass.value(BytecodeClass.java:25)
	at org.cactoos.scalar.Checked.value(Checked.java:56)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:44)
	at benchmarks.ProgramsBench.<init>(ProgramsBench.java:55)
	at benchmarks.jmh_generated.ProgramsBench_jmhType_B1.<init>(ProgramsBench_jmhType_B1.java:3)
	at benchmarks.jmh_generated.ProgramsBench_jmhType_B2.<init>(ProgramsBench_jmhType_B2.java:3)
	at benchmarks.jmh_generated.ProgramsBench_jmhType_B3.<init>(ProgramsBench_jmhType_B3.java:2)
	at benchmarks.jmh_generated.ProgramsBench_jmhType.<init>(ProgramsBench_jmhType.java:2)
	at benchmarks.jmh_generated.ProgramsBench_scansLargeProgram_jmhTest._jmh_tryInit_f_programsbench0_G(ProgramsBench_scansLargeProgram_jmhTest.java:355)
	at benchmarks.jmh_generated.ProgramsBench_scansLargeProgram_jmhTest.scansLargeProgram_AverageTime(ProgramsBench_scansLargeProgram_jmhTest.java:142)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:527)
	at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:504)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.io.IOException: The resource "program-0.xmir" was not found in jdk.internal.loader.ClassLoaders$AppClassLoader@2c854dc5 (jdk.internal.loader.ClassLoaders.AppClassLoader)
	at org.cactoos.io.ResourceOf.lambda$new$3(ResourceOf.java:148)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:38)
	at org.cactoos.scalar.Checked.value(Checked.java:56)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:44)
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:38)
	at org.cactoos.io.ResourceOf.stream(ResourceOf.java:219)
	at org.cactoos.io.TeeInput.stream(TeeInput.java:848)
	at org.cactoos.bytes.InputAsBytes.asBytes(InputAsBytes.java:59)
	at org.cactoos.bytes.BytesOf.asBytes(BytesOf.java:732)
	at org.cactoos.scalar.ScalarWithFallback.value(ScalarWithFallback.java:68)
	... 27 more
```

Let's fix it

### PR DESCRIPTION
**Pull request by h1alexbel**
In this PR I've fixed the issue with `ProgramsBench.scansLargeProgram()` benchmark run, now benchmark using L sized program from `ProgramSize.java`. Also, I added benchmark reporting in PRs via [jmh-benchmark-action](https://github.com/volodya-lombrozo/jmh-benchmark-action).

closes #478

### CODE REVIEW

**Comment by h1alexbel** [comment]
@volodya-lombrozo could take a look, please?

**Review by volodya-lombrozo — CHANGES_REQUESTED** [review]
@h1alexbel Thank you for the contribution! Are you solving the https://github.com/objectionary/lints/issues/470 issue? or the the https://github.com/objectionary/lints/issues/478?
I would highly recommend you creating a single PR for a single issue. At least, next time. Otherwise you make a scope of a PR too broad, which makes it hard to review.

File: src/test/java/benchmarks/ProgramsBench.java [hunk 1]
```diff
@@ -51,7 +52,7 @@ public ProgramsBench() {
                 final String name = String.format("program-%d.xmir", idx);
                 Files.write(
                     this.home.resolve(String.format("%s.xmir", name)),
-                    new IoChecked<>(new BytecodeClass(name))
+                    new IoChecked<>(new BytecodeClass(name, ProgramSize.L.java()))
```
[the remark this answers is not in the document]
Comment (h1alexbel) [reply src/test/java/benchmarks/ProgramsBench.java:55]: @volodya-lombrozo they were green, since we didn't run `mvn jmh:benchmark` there. To show that now its working as expected, I added missing `jmh` action. WDYT? Maybe I missing something.

**Review by volodya-lombrozo — APPROVED** [review]
@h1alexbel Looks good to me. Thank you!

**Comment by h1alexbel** [comment]
@yegor256 take a look, please

File: .github/workflows/jmh-benchmark.yml [hunk 2]
```diff
@@ -0,0 +1,21 @@
+# SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
+# SPDX-License-Identifier: MIT
+---
+name: Performance Regression Check
```
Comment (yegor256) [inline .github/workflows/jmh-benchmark.yml:4]: @h1alexbel just `benchmark` is enough. Moreover, I suggest keeping names consistent: file name, workflow name, and job name -- all three should be the same.

File: .github/workflows/jmh-comment.yml [hunk 3]
```diff
@@ -0,0 +1,35 @@
+# SPDX-FileCopyrightText: Copyright (c) 2016-2025 Objectionary.com
+# SPDX-License-Identifier: MIT
+---
+name: Post Benchmark Comment
```
Comment (yegor256) [inline .github/workflows/jmh-comment.yml:4]: @h1alexbel the same here, let's keep all three identical: file name, workflow name, and job name

**Review by yegor256 — CHANGES_REQUESTED** [review]
@h1alexbel many thanks for the contribution! A few suggestions above.

File: .github/workflows/jmh-benchmark.yml (hunk 2 above)
Comment (h1alexbel) [reply .github/workflows/jmh-benchmark.yml]: @yegor256 since `benchmark` is already reserved, let's use `jmh`.

**Comment by 0crat** [comment]
@h1alexbel Thanks for your contribution! Here's the breakdown of your +4 points: +4 base, -16 for no code review, +16 to meet the minimum. While we appreciate your effort, remember that [code reviews](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) are crucial for quality. Your balance is now [+124](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep improving and contributing!
