### PR TITLE
bug(#447): `LtUnlintNonExistingDefect` and `LtUnlintNonExistingDefectWpa` understand unlints with line number

### LINKED ISSUE #447: `unlint-non-existing-defect` does not understand `+unlint` with line number
When linting this program with `comment-not-capitalized` defect on line `3` and expect no defects:

```eo
+unlint comment-not-capitalized:3

# its foo.
[] > foo
```

But getting this:

```text
Unlinting rule 'comment-not-capitalized:3' doesn't make sense, since there are no defects with it
```

Looks like `unlint-non-existing-defect` lint (both in single and WPA scopes) does not understand unlints with line number. Let's fix it

### PR DESCRIPTION
**Pull request by h1alexbel**
In this PR I've added support of unlints with line number via `DefectMissing.java` in both: `LtUnlintNonExistingDefect` and `LtUnlintNonExistingDefectWpa`.

closes #447
History:
- **bug(#447): tests**
- **bug(#447): filters correctly in single scope**
- **bug(#447): matches in WPA**
- **bug(#447): more test**
- **bug(#447): check if present**
- **bug(#447): MatchesLinedUnlint**
- **bug(#447): clean for qulice**

### CODE REVIEW

**Comment by h1alexbel** [comment]
@maxonfjvipon please check

**Comment by h1alexbel** [comment]
@maxonfjvipon reminder

File: src/main/java/org/eolang/lints/DefectMissing.java [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+import java.util.Map;
+import java.util.Set;
+import org.cactoos.Func;
+import org.cactoos.set.SetOf;
+
+/**
+ * Does defect missing.
+ * @since 0.0.44
+ */
+final class DefectMissing implements Func<String, Boolean> {
```
Comment (maxonfjvipon) [inline src/main/java/org/eolang/lints/DefectMissing.java:18]: @h1alexbel since your `apply` method does not throw any exception, let's implement `Function` instead of `Func`

File: src/main/java/org/eolang/lints/LtUnlintNonExistingDefect.java [hunk 2]
```diff
@@ -60,13 +64,13 @@ public String name() {
...
         final Collection<Defect> defects = new LinkedList<>();
-        final Collection<String> present = this.existingDefects(xmir);
+        final Map<String, List<Integer>> present = this.existingDefects(xmir);
         final Xnav xml = new Xnav(xmir.inner());
         final Set<String> unlints = xml.path("/program/metas/meta[head='unlint']/tail")
             .map(xnav -> xnav.text().get())
             .collect(Collectors.toSet());
         unlints.stream()
-            .filter(unlint -> !present.contains(unlint) && !this.excluded.contains(unlint))
+            .filter(unlint -> new DefectMissing(present, this.excluded).apply(unlint))
```
Comment (maxonfjvipon) [inline src/main/java/org/eolang/lints/LtUnlintNonExistingDefect.java:73]: @h1alexbel I think this `new DefectMissing` may be created outside of `.filter` method

File: src/main/java/org/eolang/lints/LtUnlintNonExistingDefectWpa.java [hunk 3]
```diff
@@ -68,16 +69,16 @@ public String name() {
...
             xmir -> {
                 final Xnav xml = new Xnav(xmir.inner());
-                final List<String> present = existing.get(xmir);
+                final Map<String, List<Integer>> present = existing.get(xmir);
                 xml.path("/program/metas/meta[head='unlint']/tail")
                     .map(xnav -> xnav.text().get())
                     .collect(Collectors.toSet())
                     .stream()
-                    .filter(unlint -> !present.contains(unlint) && !this.excluded.contains(unlint))
+                    .filter(unlint -> new DefectMissing(present, this.excluded).apply(unlint))
```
Comment (maxonfjvipon) [inline src/main/java/org/eolang/lints/LtUnlintNonExistingDefectWpa.java:81]: @h1alexbel I think this `new DefectMissing` may be created outside of `.filter` method

File: src/test/java/org/eolang/lints/DefectMissingTest.java [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+
+/**
+ * Tests for {@link DefectMissing}.
+ *
+ * @since 0.0.44
+ */
+final class DefectMissingTest {
+
+    @Test
+    void returnsTrueOnMatch() {
```
Comment (maxonfjvipon) [inline src/test/java/org/eolang/lints/DefectMissingTest.java:22]: @h1alexbel the test name does not match with the result returned by `apply` function. The same story in the test below

**Review by maxonfjvipon — CHANGES_REQUESTED** [review]

**Comment by h1alexbel** [comment]
@maxonfjvipon updated. Take a look, please

**Review by maxonfjvipon — APPROVED** [review]

**Comment by h1alexbel** [comment]
@yegor256 take a look, please

**Review by yegor256 — APPROVED** [review]

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
@maxonfjvipon 🌟 Great job on the review! You've earned **+4 points**, boosting your balance to [+100](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the excellent work and watch your points grow! 💪

**Comment by 0crat** [comment]
@yegor256 Great job on the review! 🌟 You've earned +4 points, boosting your balance to [-731](https://www.eolang.org/zerocracy/objectionary-vitals.html). Keep up the excellent work and watch your score grow!

**Comment by 0crat** [comment]
@h1alexbel Thanks for your contribution! Here's the breakdown of your +4 points: +4 base, +13.2 for 264 [hits-of-code](https://www.yegor256.com/2014/11/14/hits-of-code.html), -8 for exceeding 200 HOC, and -5.2 to cap at 4 points. While the high HOC count affected your score, we appreciate your effort. [Keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) the contributions coming, aiming for concise, impactful code. Your running balance is now [+73](https://www.eolang.org/zerocracy/objectionary-vitals.html). 🚀
